language: node_js
node_js:
  - "6"
  - "7"
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 8
cache:
  directories:
  - node_modules # NPM packages
install: npm install
before_script:
    - npm install -g gulp-cli
    - npm install -g gulp
script:
